using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;
using System.Security;
using PowerShellTools.Common;

namespace PowerShellTools.Commands.UserInterface
{
    /// <summary>
    /// Data structure to provide template definitions and values from the parameter file
    /// </summary>
    internal class ScriptParameterViewModel : ObservableObject, IPasswordBoxBindingSource, INotifyDataErrorInfo
    {
        private const string ValuePropertyName = "Value";

        private List<object> _allowedValues;
        private object _value;

        public ScriptParameterViewModel(ScriptParameter parameterDefinition)
        {
            this.ParameterDefinition = Arguments.ValidateNotNull(parameterDefinition, "parameterDefinition");

            // Determine parameter type
            if (DoParameterTypeNamesMatch(ParameterDefinition.Type, ScriptParameter.BoolType))
            {
                this.Type = ParameterType.Boolean;
            }
            else if (DoParameterTypeNamesMatch(parameterDefinition.Type, ScriptParameter.SwitchType))
            {
                this.Type = ParameterType.Switch;
            }
            else if (DoParameterTypeNamesMatch(ParameterDefinition.Type, ScriptParameter.Int32Type) ||
                DoParameterTypeNamesMatch(parameterDefinition.Type, ScriptParameter.Int64Type))
            {
                this.Type = ParameterType.Integer;
            }
            else if (DoParameterTypeNamesMatch(ParameterDefinition.Type, ScriptParameter.StringType))
            {
                this.Type = ParameterType.String;
            }
            else if (DoParameterTypeNamesMatch(ParameterDefinition.Type, ScriptParameter.SecureStringType))
            {
                this.Type = ParameterType.SecureString;
            }
            else
            {
                this.Type = ParameterType.Unknown;
            }
            
            Validate();
        }

        /// <summary>
        /// Copy constructor.
        /// </summary>
        /// <param name="source">The instance to copy.</param>
        public ScriptParameterViewModel(ScriptParameterViewModel source)
            : this(source.ParameterDefinition)
        {
            Debug.Assert(source != null, "templateParameterValue should not be null");
            this.Value = source.Value;
        }
        
        /// <summary>
        /// The definition of the parameter in the template file
        /// </summary>
        private ScriptParameter ParameterDefinition
        {
            get;
            set;
        }

        public string Name
        {
            get { return ParameterDefinition.Name; }
        }

        public ParameterType Type
        {
            get;
            private set;
        }

        public object Value
        {
            get
            {
                return _value;
            }
            set
            {
                if (this.Type == ParameterType.SecureString)
                {
                    // Use SecureString in the UI layer.  If a securestring is in the template or parameters
                    //   file, we can't control that. However, we can at least use SecureString in the UI layer
                    //   if the user enters a new one.
                    var stringValue = value as string;
                    if (stringValue != null)
                    {
                        value = stringValue.ToSecureString();
                    }
                }
                _value = value;

                Validate();
                NotifyPropertyChanged();
                NotifyPropertyChanged("Watermark");
            }
        }

        /// <summary>
        /// Give a list of allowed values appropriate for UI display purposes 
        /// </summary>
        public IEnumerable<object> AllowedValues
        {
            get
            {
                EnsureAllowedValues();
                return _allowedValues;
            }
        }

        /// <summary>
        /// Indicates a watermark that should be displayed if the parameter's value
        /// is null or empty string.
        /// </summary>
        public string Watermark
        {
            get
            {
                //if (this.ParameterDefinition.IsAutoGenerated)
                //{
                //    return Resources.WatermarkAutoGenerated;
                //}
                //else
                //{
                    if (this.Value == null)
                    {
                        return Resources.WatermarkNull;
                    }
                    else
                    {
                        return null;
                    }

                //}
            }
        }

        public override string ToString()
        {
            return this.Name;
        }

        /// <summary>
        /// Populate the allowed values as appropriate for the UI, always including null and 
        /// the current value even if they are not included in the CSM model's allowed value
        /// enumeration...
        /// </summary>
        private void EnsureAllowedValues()
        {
            Debug.Assert(ParameterDefinition != null, "You should not be able to create an instance without a backing ParameterDefinition");

            if (_allowedValues == null)
            {
                _allowedValues = new List<object>();
                if (ParameterDefinition.AllowedValues.Count > 0)
                {
                    _allowedValues.AddRange(ParameterDefinition.AllowedValues);
                }
                else if (this.Type == ParameterType.Boolean)
                {
                    _allowedValues.Add(true);
                    _allowedValues.Add(false);
                }
                else if (this.Type == ParameterType.Switch)
                {
                    _allowedValues.Add("On");
                    _allowedValues.Add("Off");
                }
                if (_allowedValues.Count > 0)
                {
                    // If the current value is not in the list of allowed values, we have to
                    //   add it or it won't show up in the dropdowns.
                    if (!_allowedValues.Contains(Value))
                    {
                        _allowedValues.Insert(0, Value);
                    }
                }
            }
        }

        /// <summary>
        /// Determines whether two template parameter type names match
        /// </summary>
        /// <param name="typeName1">Type name 1</param>
        /// <param name="typeName2">Type name 2</param>
        /// <returns>True if they match</returns>
        private bool DoParameterTypeNamesMatch(string typeName1, string typeName2)
        {
            return string.Equals(typeName1, typeName2, StringComparison.OrdinalIgnoreCase);
        }

        #region IPasswordBoxBindingSource implementation

        SecureString IPasswordBoxBindingSource.SecurePassword
        {
            // Used for databinding to PasswordBox
            get
            {
                return this.Value as SecureString;
            }
            set
            {
                this.Value = value as SecureString;
            }
        }

        #endregion

        #region Validation

        /// <summary>
        /// Sets the Error and Warning properties appropriately
        /// </summary>
        private void Validate()
        {
            string warning = null;
            string error = null;

            if (!IsValidType())
            {
                error = Resources.Error_TypeMismatch_2args
                    .FormatCurrentCulture(this.Name, this.ParameterDefinition.Type);
            }
            else if (!IsAllowedValue())
            {
                error = Resources.Error_DisallowedValue_1arg.FormatCurrentCulture(this.Name);
            }

            // Set the validation error to either an error or warning
            if (error != null)
            {
                this.ValidationResult = new ValidationResult()
                {
                    Message = error
                };
            }
            else if (warning != null)
            {
                this.ValidationResult = new ValidationResult()
                {
                    Message = warning,
                    IsWarning = true
                };
            }
            else
            {
                this.ValidationResult = null;
            }

            // Fire changed events
            if (this.ErrorsChanged != null)
            {
                ErrorsChanged(this, new DataErrorsChangedEventArgs(ValuePropertyName));
            }
            NotifyPropertyChanged("HasWarning");
            NotifyPropertyChanged("HasError");
            NotifyPropertyChanged("HelpText");
        }

        /// <summary>
        /// True if the current parameter value falls within the allowed
        ///   values.
        /// </summary>
        /// <returns></returns>
        private bool IsAllowedValue()
        {
            if (!this.ParameterDefinition.AllowedValues.Any())
            {
                return true;
            }

            return this.ParameterDefinition.AllowedValues.Any(allowed =>
                ParameterValueComparer.AreParameterValuesEqual(this.Value, allowed));
        }

        /// <summary>
        /// True if the current parameter value is of the correct type
        /// </summary>
        /// <returns></returns>
        private bool IsValidType()
        {
            if (this.Value == null)
                return true;

            switch (this.Type)
            {
                case ParameterType.Boolean:
                    return this.Value is bool;

                case ParameterType.Switch:
                    string value = this.Value.ToString();
                    return value.Equals("On", StringComparison.Ordinal) || value.Equals("Off", StringComparison.Ordinal);

                case ParameterType.Integer:
                    return this.Value is int;

                case ParameterType.SecureString:
                case ParameterType.String:
                    return this.Value is SecureString || this.Value is string;

                case ParameterType.Unknown:
                    return true;

                default:
                    Debug.Fail("Unexpected type");
                    return true;
            }
        }

        #region Errors/Warnings

        /// <summary>
        /// The current error, if any, or null
        /// </summary>
        public ValidationResult ValidationResult
        {
            get;
            private set;
        }

        /// <summary>
        /// A string appropriate for help text for screen readers
        /// </summary>
        public string HelpText
        {
            get
            {
                return (this.ValidationResult == null ? null : ValidationResult.Message)
                    ?? this.Watermark;
            }
        }

        public bool HasValidationResult
        {
            get { return this.ValidationResult != null; }
        }

        public bool HasError
        {
            get { return this.ValidationResult != null && !this.ValidationResult.IsWarning; }
        }

        public bool HasWarning
        {
            get { return this.ValidationResult != null && this.ValidationResult.IsWarning; }
        }

        #endregion IDataErrorInfo implementation

        #region INotifyDataErrorInfo implementation

        public event EventHandler<DataErrorsChangedEventArgs> ErrorsChanged;

        IEnumerable INotifyDataErrorInfo.GetErrors(string propertyName)
        {
            // We only support a single validation error right now
            if (string.Equals(propertyName, ValuePropertyName, StringComparison.OrdinalIgnoreCase))
            {
                if (this.ValidationResult != null)
                {
                    yield return this.ValidationResult;
                }
            }
        }

        bool INotifyDataErrorInfo.HasErrors
        {
            get { return this.HasValidationResult; }
        }

        #endregion INotifyDataErrorInfo implementation

        #endregion Validation
    }
}
